# FROM python:3.7

# RUN pip install --upgrade pip

# COPY ./requirements.txt .
# RUN pip install -r requirements.txt


# # CMD python ./mysite/manage.py migrate auth \
# # && python manage.py migrate

# # CMD python ./mysite/manage.py makemigrations \
# # && python ./mysite/manage.py migrate \
# # # && python ./mysite/manage.py createsuperuser
# # && python ./mysite/manage.py runserver 0:8000

# COPY ./mysite /app

# WORKDIR /app

# COPY ./entrypoint.sh /
# ENTRYPOINT ["sh", "/entrypoint.sh"]

# FROM nginx:latest
# COPY ./custom-app.conf /etc/nginx/conf.d
# COPY ./custom-web.conf /etc/nginx/conf.d



FROM python:3.7
WORKDIR /code
ENV PYTHONUNBUFFERED=1
COPY wait.sh /wait.sh
RUN chmod +x /wait.sh
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
ADD ./ /code
CMD /wait.sh db 5432 \
  && python mysite/manage.py collectstatic --noinput \
  && python mysite/manage.py migrate \
#   && python mysite/manage.py loaddata data.json \
  && /usr/local/bin/uwsgi --ini /code/mysite/mysite/uwsgi.ini 



