version: '3'
services:

  # frontend web server
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"
    volumes:
      - ./:/code:ro

  # database server
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: secret

