
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      # - "8000:8000"
      - "8080:8080"
    volumes:
      - ./:/code:rw
    environment:
      DJANGO_MODE: devel # look at os.environ['DJANGO_MODE'] to detect deployment

      