

FROM python:3.7
WORKDIR /code
ENV PYTHONUNBUFFERED=1
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
CMD python contact_manager/manage.py migrate \
  # && python contact_manager/manage.py loaddata data.json \
  # && python contact_manager/manage.py runserver 0:8000
  && python contact_manager/manage.py runserver 0:8080

