FROM node:15.13-alpine as build
WORKDIR /client
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# production environment
FROM nginx:latest
COPY --from=build /client/build /usr/share/nginx/html
COPY --from=build /client/nginx/nginx-setup.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]